# Generated by Django 3.2.3 on 2021-05-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dogs',
            new_name='Dog',
        ),
    ]
